import type { AgentSummary, Message, RuntimeStatus } from '../shared/contracts'

export const mockRuntimeStatus: RuntimeStatus = {
  mode: 'mock',
  label: 'Mock runtime healthy',
  health: 'healthy',
  tracker: 'healthy',
  registry: 'healthy',
  tmux: 'healthy',
  updatedAt: '2026-05-25T13:30:00.000Z',
  notes: [
    'Fixture data only; no agent-tracker socket is opened.',
    'Registry and tmux health are simulated for UX exploration.',
  ],
}

export const mockAgents: AgentSummary[] = [
  {
    id: 'local-main',
    name: 'main',
    displayName: 'main',
    scope: 'local',
    status: 'idle',
    cwd: '/home/tanmay/projects/nix/broccoli-comms',
    project: 'broccoli-comms',
    address: 'main',
    unread: 2,
    lastActiveAt: '2026-05-25T13:18:00.000Z',
    conversationKey: 'main',
    canDirectControl: true,
    tags: ['local', 'primary'],
  },
  {
    id: 'local-reviewer',
    name: 'broccoli-comms-electron-reviewer',
    displayName: 'electron reviewer',
    scope: 'local',
    status: 'waiting',
    cwd: '/home/tanmay/projects/nix/broccoli-comms-electron-worktree',
    project: 'broccoli-comms',
    address: 'broccoli-comms-electron-reviewer',
    unread: 0,
    lastActiveAt: '2026-05-25T13:12:00.000Z',
    conversationKey: 'broccoli-comms-electron-reviewer',
    canDirectControl: true,
    tags: ['review'],
  },
  {
    id: 'local-coder',
    name: 'broccoli-comms-agent-1',
    displayName: 'mock app coder',
    scope: 'local',
    status: 'busy',
    cwd: '/home/tanmay/projects/nix/broccoli-comms-electron-worktree',
    project: 'broccoli-comms',
    address: 'broccoli-comms-agent-1',
    unread: 1,
    lastActiveAt: '2026-05-25T13:21:00.000Z',
    conversationKey: 'broccoli-comms-agent-1',
    canDirectControl: true,
    tags: ['implementation'],
  },
  {
    id: 'remote-dawnstar-knowledge',
    name: 'dawnstar/agent_knowledge-agent-1',
    displayName: 'dawnstar knowledge',
    scope: 'remote',
    status: 'idle',
    cwd: '/home/tanmay/agent_knowledge',
    project: 'agent_knowledge',
    address: 'dawnstar/agent_knowledge-agent-1',
    unread: 0,
    lastActiveAt: '2026-05-25T11:03:00.000Z',
    conversationKey: 'dawnstar/agent_knowledge-agent-1',
    canDirectControl: false,
    tags: ['remote', 'registry'],
  },
  {
    id: 'remote-mac-hm-core',
    name: 'mac/hm-core-coder',
    displayName: 'mac hm-core',
    scope: 'remote',
    status: 'offline',
    cwd: '/Users/tanmayvijay/home-manager-core',
    project: 'home-manager-core',
    address: 'mac/hm-core-coder',
    unread: 0,
    lastActiveAt: '2026-05-24T20:10:00.000Z',
    conversationKey: 'mac/hm-core-coder',
    canDirectControl: false,
    tags: ['remote', 'offline'],
  },
]

export const mockMessages: Record<string, Message[]> = {
  'main': [
    {
      id: 'msg-main-1',
      conversationKey: 'main',
      direction: 'inbound',
      author: 'main',
      recipient: 'you',
      body: 'I finished reviewing the direct-input plan. Want me to start the next chunk?',
      createdAt: '2026-05-25T12:40:00.000Z',
      deliveryState: 'received',
    },
    {
      id: 'msg-main-2',
      conversationKey: 'main',
      direction: 'outbound',
      author: 'you',
      recipient: 'main',
      body: 'Yes — keep direct pane control conservative, explicit, and default-disabled for remote agents.',
      createdAt: '2026-05-25T12:41:00.000Z',
      deliveryState: 'delivered',
    },
    {
      id: 'msg-main-3',
      conversationKey: 'main',
      direction: 'system',
      author: 'mock runtime',
      recipient: 'you',
      body: 'Direct pane-control actions are mocked here and do not write normal message history.',
      createdAt: '2026-05-25T12:42:00.000Z',
      deliveryState: 'received',
    },
  ],
  'broccoli-comms-electron-reviewer': [
    {
      id: 'msg-reviewer-1',
      conversationKey: 'broccoli-comms-electron-reviewer',
      direction: 'inbound',
      author: 'broccoli-comms-electron-reviewer',
      recipient: 'you',
      body: 'Ready to review the Electron mock scaffold once Chunk E1 is complete.',
      createdAt: '2026-05-25T13:12:00.000Z',
      deliveryState: 'received',
    },
  ],
  'broccoli-comms-agent-1': [
    {
      id: 'msg-coder-1',
      conversationKey: 'broccoli-comms-agent-1',
      direction: 'inbound',
      author: 'broccoli-comms-agent-1',
      recipient: 'you',
      body: 'Scaffolding the mock Electron app with local fixture data only.',
      createdAt: '2026-05-25T13:21:00.000Z',
      deliveryState: 'received',
    },
  ],
  'dawnstar/agent_knowledge-agent-1': [
    {
      id: 'msg-dawnstar-1',
      conversationKey: 'dawnstar/agent_knowledge-agent-1',
      direction: 'inbound',
      author: 'dawnstar/agent_knowledge-agent-1',
      recipient: 'you',
      body: 'Remote agent visible through registry-shaped fixture data. Direct pane control is disabled in this mock.',
      createdAt: '2026-05-25T11:03:00.000Z',
      deliveryState: 'received',
    },
  ],
  'mac/hm-core-coder': [
    {
      id: 'msg-mac-1',
      conversationKey: 'mac/hm-core-coder',
      direction: 'system',
      author: 'mock runtime',
      recipient: 'you',
      body: 'Remote tracker is offline/unknown. Messaging UI remains visible for design exploration.',
      createdAt: '2026-05-24T20:10:00.000Z',
      deliveryState: 'received',
    },
  ],
}
